// src/identity/entities/web-proof.entity.ts
// Stores GitHub OAuth-sourced contributor data and EAS attestation output.
// The backend acts as a trusted oracle: authenticates via GitHub OAuth,
// fetches rich contributor data, and issues an on-chain EAS attestation.
//
// Status machine:
//   PENDING → OAUTH_COMPLETE → DATA_FETCHED → ATTESTED → VERIFIED → FAILED

import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

export enum ProofStatus {
  PENDING = 'pending', // initVerification called, waiting for OAuth
  OAUTH_COMPLETE = 'oauth_complete', // GitHub OAuth code exchanged for token
  DATA_FETCHED = 'data_fetched', // All GitHub API data fetched and persisted
  ATTESTED = 'attested', // EAS attestation submitted on-chain
  VERIFIED = 'verified', // Frontend confirmed additional on-chain action
  FAILED = 'failed', // Any step failed — see errorMessage
}

@Entity('web_proofs')
export class WebProof {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // UUID generated by the frontend before starting verification.
  // Used as OAuth `state` parameter to prevent CSRF.
  @Index({ unique: true })
  @Column({ name: 'request_id' })
  requestId: string;

  // The wallet that initiated this verification.
  @Index()
  @Column({
    name: 'wallet_address',
    nullable: true,
    type: 'varchar',
    length: 42,
  })
  walletAddress: string | null;

  // ── GitHub data fields (fetched via OAuth token) ───────────────────────────

  @Column({ name: 'github_login', nullable: true, type: 'varchar' })
  githubLogin: string | null;

  @Column({ name: 'github_id', nullable: true, type: 'bigint' })
  githubId: number | null;

  @Column({ name: 'github_created_at', nullable: true, type: 'timestamptz' })
  githubCreatedAt: Date | null;

  @Column({ name: 'github_created_year', nullable: true, type: 'int' })
  githubCreatedYear: number | null;

  @Column({ name: 'account_age_seconds', nullable: true, type: 'bigint' })
  accountAgeSeconds: number | null;

  @Column({ name: 'public_repos', nullable: true, type: 'int' })
  publicRepos: number | null;

  @Column({ name: 'total_stars', nullable: true, type: 'int' })
  totalStars: number | null;

  @Column({ name: 'followers', nullable: true, type: 'int' })
  followers: number | null;

  @Column({ name: 'commit_count', nullable: true, type: 'int' })
  commitCount: number | null;

  @Column({ name: 'contribution_events_90d', nullable: true, type: 'int' })
  contributionEvents90d: number | null;

  @Column({ name: 'public_gists', nullable: true, type: 'int' })
  publicGists: number | null;

  // Top languages across all repos
  @Column({ name: 'languages', type: 'simple-array', nullable: true })
  languages: string[] | null;

  // Org names the user belongs to
  @Column({ name: 'orgs', type: 'simple-array', nullable: true })
  orgs: string[] | null;

  @Column({ name: 'contribution_tier', nullable: true, type: 'varchar' })
  contributionTier: string | null;

  // ── ZK Oracle Output ───────────────────────────────────────────────────────

  // The 64-byte raw ECDSA signature from the backend Oracle
  @Column({
    name: 'oracle_signature',
    nullable: true,
    type: 'varchar',
    length: 132,
  })
  oracleSignature: string | null;

  // The keccak256 hash of the GitHub data that was signed
  @Column({ name: 'message_hash', nullable: true, type: 'varchar', length: 66 })
  messageHash: string | null;

  // ── OAuth intermediate (cleared after attestation) ─────────────────────────

  @Column({ name: 'oauth_access_token', nullable: true, type: 'text' })
  oauthAccessToken: string | null;

  // ── Legacy / compatibility ─────────────────────────────────────────────────

  // Raw payload stored for debugging (JSON blob)
  @Column({ type: 'jsonb', nullable: true })
  payload: Record<string, any> | null;

  // ── Status ─────────────────────────────────────────────────────────────────

  @Column({
    type: 'enum',
    enum: ProofStatus,
    default: ProofStatus.PENDING,
  })
  status: ProofStatus;

  // Error message stored when status = FAILED
  @Column({ name: 'error_message', nullable: true, type: 'text' })
  errorMessage: string | null;

  // On-chain transaction hash after any additional frontend submission
  @Column({ name: 'tx_hash', nullable: true, type: 'varchar', length: 66 })
  txHash: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
